name: PlatformIO CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup PlatformIO
        uses: n-vr/setup-platformio-action@v1

      - name: Build PlatformIO project
        run: |
          cd "Software/Source code"
          pio run
        
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: platformio-build
          path: .pio/build/megaatmega2560/firmware.hex