name: PlatformIO CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  # Check if PlatformIO is installed
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Run setup
        run: pwd

  # Build the PlatformIO project
  build:
    runs-on: ubuntu-latest

    steps:
     # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Setup PlatformIO in PATH
      - name: Setup PlatformIO
        uses: n-vr/setup-platformio-action@v1
      
      # Build the PlatformIO project
      - name: Build PlatformIO project
        run: cd Software/Electrospining && pio run
      
      # Upload build artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: platformio-build
          path: build
      
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: platformio-build
          path: build
      
      - name: Test PlatformIO project
        run: cd Software/Electrospining && pio test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying..."

  